### ISSUE TITLE
mapping values

### ISSUE THREAD

**Issue by cdn4lf** [Sennevds/system_sensors#121]
I'm trying to run this on ubuntu 20.04 and am getting the following errors.
```Traceback (most recent call last):
  File "src/system_sensors.py", line 187, in <module>
    settings = yaml.safe_load(f)
  File "/home/user/.local/lib/python3.8/site-packages/yaml/__init__.py", line 16                                                                                                                                                             2, in safe_load
    return load(stream, SafeLoader)
  File "/home/user/.local/lib/python3.8/site-packages/yaml/__init__.py", line 11                                                                                                                                                             4, in load
    return loader.get_single_data()
  File "/home/user/.local/lib/python3.8/site-packages/yaml/constructor.py", line                                                                                                                                                              49, in get_single_data
    node = self.get_single_node()
  File "/home/user/.local/lib/python3.8/site-packages/yaml/composer.py", line 36                                                                                                                                                             , in get_single_node
    document = self.compose_document()
  File "/home/user/.local/lib/python3.8/site-packages/yaml/composer.py", line 55                                                                                                                                                             , in compose_document
    node = self.compose_node(None, None)
  File "/home/user/.local/lib/python3.8/site-packages/yaml/composer.py", line 84                                                                                                                                                             , in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/user/.local/lib/python3.8/site-packages/yaml/composer.py", line 12                                                                                                                                                             7, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/user/.local/lib/python3.8/site-packages/yaml/parser.py", line 98,                                                                                                                                                              in check_event
    self.current_event = self.state()
  File "/home/user/.local/lib/python3.8/site-packages/yaml/parser.py", line 428,                                                                                                                                                              in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/user/.local/lib/python3.8/site-packages/yaml/scanner.py", line 116                                                                                                                                                             , in check_token
    self.fetch_more_tokens()
  File "/home/user/.local/lib/python3.8/site-packages/yaml/scanner.py", line 223                                                                                                                                                             , in fetch_more_tokens
    return self.fetch_value()
  File "/home/user/.local/lib/python3.8/site-packages/yaml/scanner.py", line 577                                                                                                                                                             , in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "src/settings.yaml", line 3, column 7
```

**Comment by Sennevds** [comment]
Your settings file is incorrect. Check indentation

**Comment by cdn4lf** [comment]
You are correct.  Somehow my I screwed up something.
