### ISSUE TITLE
Getting error on two differents rpis

### ISSUE THREAD

**Issue by WLCD** [Sennevds/system_sensors#98]
Hello,

I'm installing the script on several Raspis, it works flawlessly on one already, but two other units are giving me trouble here are their outputs 

Raspi  4
`Traceback (most recent call last):
  File "src/system_sensors.py", line 708, in <module>
    mqttClient.connect(settings["mqtt"]["hostname"], settings["mqtt"]["port"])
  File "/home/admin/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/home/admin/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1115, in reconnect
    return self._send_connect(self._keepalive)
  File "/home/admin/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2611, in _send_connect
    1 + 2 + 2 + len(self._client_id)
TypeError: object of type 'int' has no len()`

Raspi 3
`Traceback (most recent call last):
  File "src/system_sensors.py", line 708, in <module>
    mqttClient.connect(settings["mqtt"]["hostname"], settings["mqtt"]["port"])
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1115, in reconnect
    return self._send_connect(self._keepalive)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2611, in _send_connect
    1 + 2 + 2 + len(self._client_id)
TypeError: object of type 'int' has no len()`

Both are up to date :/

**Comment by WLCD** [comment]
Solved the issue, don't put 1 as value for client_id.
